[package]
name = "packet_sniffer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
ctrlc = "3.4.7"
pnet = "0.35.0"
nix = { version = "0.30.1", features = ["user"] }
